"""OzzyDB Python Client."""

__version__ = "0.3.0"

from .client import (
    create_bundle_artifact,
    create_collection_artifact,
    declare_conformance,
    download_artifact,
    fetch,
    fetch_lazy,
    get_artifact,
    get_artifact_conformance,
    inspect,
    list_artifacts,
    list_endpoints,
    upload_artifact,
)
from .http import OzzyApiError, OzzyClient
from .types import (
    ArtifactConformance,
    ArtifactDetail,
    ArtifactManifest,
    ArtifactManifestEntry,
    ArtifactSummary,
    ConformanceRecordDetail,
    DagResponse,
    EdgeDetail,
    EndpointDetail,
    EndpointSummary,
    NodeDetail,
    ParamDetail,
    ParamSummary,
    TransformEnvironmentRef,
    TransformInspection,
    TypeRefDetail,
    TypeVersionDetail,
    TypedPortDetail,
    UploadArtifactResult,
    VerificationAttemptDetail,
)

__all__ = [
    "fetch",
    "fetch_lazy",
    "inspect",
    "list_endpoints",
    "upload_artifact",
    "list_artifacts",
    "get_artifact",
    "download_artifact",
    "create_bundle_artifact",
    "create_collection_artifact",
    "get_artifact_conformance",
    "declare_conformance",
    "OzzyClient",
    "OzzyApiError",
    "ArtifactConformance",
    "ArtifactDetail",
    "ArtifactManifest",
    "ArtifactManifestEntry",
    "ArtifactSummary",
    "ConformanceRecordDetail",
    "DagResponse",
    "EdgeDetail",
    "EndpointDetail",
    "EndpointSummary",
    "NodeDetail",
    "ParamDetail",
    "ParamSummary",
    "TransformEnvironmentRef",
    "TransformInspection",
    "TypeRefDetail",
    "TypeVersionDetail",
    "TypedPortDetail",
    "UploadArtifactResult",
    "VerificationAttemptDetail",
]
